# Generated by Django 3.0.7 on 2020-06-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
