# Generated by Django 3.0.7 on 2020-06-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.CharField(default='shy73', max_length=30),
        ),
    ]
