# Generated by Django 3.0.7 on 2020-06-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
