# Generated by Django 3.0.7 on 2020-06-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='writer',
            field=models.CharField(default='admin', max_length=30),
        ),
    ]
