# Generated by Django 3.0.7 on 2020-06-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('imgurl', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='description',
        ),
    ]
