# Generated by Django 3.0.7 on 2020-06-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_imageuploadmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='username',
        ),
    ]
