# Generated by Django 3.0.7 on 2020-06-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_remove_imageuploadmodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploadmodel',
            name='blog_id',
            field=models.IntegerField(default=0),
        ),
    ]
