# Generated by Django 3.0.7 on 2020-06-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0010_auto_20200614_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='uploader_id',
        ),
    ]
